stages:
  - deploy

deploy:
  stage: deploy
  script:
    - git remote add github https://github.com/yashthakkar2700/Spring-Boot-Learning
    - git config user.name "yashthakkar2700"
    - git config user.email "yashthakkar2700@gmail.com"
    - git fetch github
    - git push github master  # Push to GitHub (adjust the branch name if needed)
  only:
    - master  # Only run on the main branch (or use your preferred branch)
