stages:
  - deploy

deploy:
  stage: deploy
  script:
    - git remote add github https://yashthakkar2700:${GITHUB_TOKEN}@github.com/yashthakkar2700/Spring-Boot-Learning.git
    - git config user.name "yashthakkar2700"
    - git config user.email "yashthakkar2700@gmail.com"
    - git checkout -b master  # Explicitly create the 'master' branch if needed
    - git fetch github
    - git push github master  # Make sure you're pushing to the correct branch
  only:
    - master  # Trigger only when pushing to 'master' branch
